title: KillQuest
description: The System Reference Document (SRD) for KillQuest
theme: just-the-docs

url: https://killquest.github.io/killquest

aux_links:
  Template Repository: https://github.com/killquest/killquest
